# infra/kong/railway.toml

[build]
builder = "dockerfile"
dockerfilePath = "dockerfile"

[deploy]
healthcheckPath = "/kong-health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3