package postgres

import (
	"context"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/willikay11/wrench/api/internal/core/domain"
)

// waitlistRepo is the Postgres-backed implementation of
// ports.WaitlistRepository. The service layer only ever sees the interface,
// so swapping this for another store never touches business logic.
type waitlistRepo struct {
	db *pgxpool.Pool
}

func NewWaitlistRepository(db *pgxpool.Pool) *waitlistRepo {
	return &waitlistRepo{db: db}
}

// Save inserts the entry and fills in the ID generated by Postgres.
// Signing up twice with the same email is not an error — we just touch the
// row and hand back the existing ID.
const saveWaitlistQuery = `
	INSERT INTO waitlist (email)
	VALUES ($1)
	ON CONFLICT (email) DO UPDATE SET updatedAt = NOW()
	RETURNING id`

func (r *waitlistRepo) Save(ctx context.Context, waitlist *domain.Waitlist) error {
	// Derive from the caller so a client disconnect cancels the query,
	// while still capping how long we can hold a pool connection.
	ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()

	// Resolve per call: joins the caller's transaction when there is one,
	// otherwise runs standalone on the pool.
	err := from(ctx, r.db).QueryRow(ctx, saveWaitlistQuery, waitlist.Email).Scan(&waitlist.ID)
	if err != nil {
		return fmt.Errorf("save waitlist entry: %w", err)
	}

	return nil
}
