// Auto-generated by Supabase CLI: supabase gen types typescript
// Run: pnpm db:types to regenerate after migrations

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          display_name: string | null
          avatar_url: string | null
          region: string | null
          created_at: string
        }
        Insert: Omit<Database["public"]["Tables"]["users"]["Row"], "created_at">
        Update: Partial<Database["public"]["Tables"]["users"]["Insert"]>
      }
      builds: {
        Row: {
          id: string
          user_id: string
          title: string
          donor_car: string | null
          engine_swap: string | null
          goals: string[]
          image_url: string | null
          vision_data: Record<string, unknown> | null
          status: "planning" | "in_progress" | "complete"
          is_public: boolean
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database["public"]["Tables"]["builds"]["Row"], "id" | "created_at" | "updated_at">
        Update: Partial<Database["public"]["Tables"]["builds"]["Insert"]>
      }
      parts: {
        Row: {
          id: string
          build_id: string
          name: string
          category: string | null
          is_safety_critical: boolean
          status: "needed" | "ordered" | "sourced" | "installed"
          notes: string | null
          created_at: string
        }
        Insert: Omit<Database["public"]["Tables"]["parts"]["Row"], "id" | "created_at">
        Update: Partial<Database["public"]["Tables"]["parts"]["Insert"]>
      }
    }
  }
}
